spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:path to db file/TestBase;INIT=RUNSCRIPT FROM 'path to init file /TestBase'
    username: sa
    password: